package com.smeal.config;
import com.smeal.security.JwtTokenProvider; import io.jsonwebtoken.Claims; import java.util.*; import org.springframework.context.annotation.*; import org.springframework.http.HttpHeaders; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.filter.OncePerRequestFilter;
@Configuration public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean SecurityFilterChain security(HttpSecurity http,JwtTokenProvider jwt,org.springframework.data.redis.core.StringRedisTemplate redis,com.fasterxml.jackson.databind.ObjectMapper mapper)throws Exception{
  OncePerRequestFilter filter=new OncePerRequestFilter(){protected void doFilterInternal(jakarta.servlet.http.HttpServletRequest req,jakarta.servlet.http.HttpServletResponse res,jakarta.servlet.FilterChain chain)throws java.io.IOException,jakarta.servlet.ServletException{String h=req.getHeader(HttpHeaders.AUTHORIZATION);if(h!=null&&h.startsWith("Bearer "))try{String raw=h.substring(7);Claims c=jwt.parse(raw);if(!Boolean.TRUE.equals(redis.hasKey("revoked:"+raw))){var auth=new UsernamePasswordAuthenticationToken(c.getSubject(),null,List.of(new SimpleGrantedAuthority("ROLE_"+c.get("role",String.class))));org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(auth);}}catch(RuntimeException ignored){}chain.doFilter(req,res);}};
  return http.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/v1/auth/register","/v1/auth/login","/v1/auth/refresh","/v1/health","/actuator/health").permitAll().anyRequest().authenticated()).exceptionHandling(e->e.authenticationEntryPoint((req,res,ex)->{res.setStatus(401);res.setContentType("application/json");mapper.writeValue(res.getOutputStream(),new com.smeal.dto.ErrorDTO(java.time.Instant.now(),401,"Authentication required",req.getRequestURI()));}).accessDeniedHandler((req,res,ex)->{res.setStatus(403);res.setContentType("application/json");mapper.writeValue(res.getOutputStream(),new com.smeal.dto.ErrorDTO(java.time.Instant.now(),403,"Access denied",req.getRequestURI()));})).addFilterBefore(filter,UsernamePasswordAuthenticationFilter.class).build();
 }
}
