package com.smeal.service;
import com.smeal.dto.*; import com.smeal.entity.User; import com.smeal.exception.BadRequestException; import com.smeal.exception.UnauthorizedException; import com.smeal.repository.UserRepository; import com.smeal.security.JwtTokenProvider; import java.time.Duration; import java.util.UUID; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
@Service public class AuthService {
 private final UserRepository users; private final PasswordEncoder encoder; private final JwtTokenProvider jwt; private final StringRedisTemplate redis; private final long refreshMs;
 public AuthService(UserRepository u,PasswordEncoder e,JwtTokenProvider j,StringRedisTemplate r,@Value("${jwt.refresh-expiration-ms}")long ms){users=u;encoder=e;jwt=j;redis=r;refreshMs=ms;}
 public AuthResponseDTO register(AuthRequestDTO a){if(users.findByEmailIgnoreCase(a.email()).isPresent())throw new BadRequestException("Email already registered");if(a.name()==null||a.name().isBlank())throw new BadRequestException("Name is required");User u=users.save(new User(a.email().toLowerCase(),encoder.encode(a.password()),a.name().trim()));return issue(u);}
 public AuthResponseDTO login(AuthRequestDTO a){User u=users.findByEmailIgnoreCase(a.email()).orElseThrow(()->new UnauthorizedException("Invalid credentials"));if(!encoder.matches(a.password(),u.getPasswordHash()))throw new UnauthorizedException("Invalid credentials");return issue(u);}
 private AuthResponseDTO issue(User u){String token=jwt.create(u.getId(),u.getEmail(),u.getRole()),refresh=UUID.randomUUID().toString();redis.opsForValue().set("refresh:"+refresh,u.getId().toString(),Duration.ofMillis(refreshMs));return new AuthResponseDTO(u.getId(),token,refresh,jwt.getExpiry()/1000);}
 public AuthResponseDTO refresh(String refresh){String id=refresh==null?null:redis.opsForValue().get("refresh:"+refresh);if(id==null)throw new UnauthorizedException("Invalid refresh token");User u=users.findById(UUID.fromString(id)).orElseThrow();redis.delete("refresh:"+refresh);return issue(u);}
 public void logout(String refresh,String access){if(refresh!=null)redis.delete("refresh:"+refresh);if(access!=null&&access.startsWith("Bearer ")){String raw=access.substring(7);try{long seconds=Math.max(1,(jwt.parse(raw).getExpiration().getTime()-System.currentTimeMillis())/1000);redis.opsForValue().set("revoked:"+raw,"1",Duration.ofSeconds(seconds));}catch(RuntimeException ignored){}}}
}
